name: Deploy Firebase App

on:
  push:
    branches:
      - main  # Ejecuta el workflow cuando hay un push en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza una máquina Ubuntu para correr el workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Obtiene el código del repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Configura la versión de Node.js

      - name: Replace Secrets in Config
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          sed -i "s|\${{ secrets.FIREBASE_API_KEY }}|$FIREBASE_API_KEY|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_AUTH_DOMAIN }}|$FIREBASE_AUTH_DOMAIN|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_PROJECT_ID }}|$FIREBASE_PROJECT_ID|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_STORAGE_BUCKET }}|$FIREBASE_STORAGE_BUCKET|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|$FIREBASE_MESSAGING_SENDER_ID|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_APP_ID }}|$FIREBASE_APP_ID|g" ./firebase-config.js
          sed -i "s|\${{ secrets.FIREBASE_MEASUREMENT_ID }}|$FIREBASE_MEASUREMENT_ID|g" ./firebase-config.js

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto

      - name: Build and Deploy
        run: npm run build  # Construye la aplicación (ajusta según tu proyecto)
